indent using 4 spaces (1/3)
As advised in I072cf8bf6748d0c910fecffdf2282bcc4656d038, code should
use 4 spaces for indentation.

This commit enforces the use of 4 spaces indentation.
In order to simplify the review process, this patch only cover the
following elements:
 - bm-dnsmasq,
 - boot-stack,
 - cinder-volume
 - devstack
 - haproxy
 - keepalived
 - mariadb
 - mariadb-dev
 - memcached
 - mysql-common
 - mysql

Change-Id: I7932fd24e72f7585e24ad3e0213f42361e668f7c

diff --git a/elements/boot-stack/bin/boot-stack-logs b/elements/boot-stack/bin/boot-stack-logs
--- a/elements/boot-stack/bin/boot-stack-logs
+++ b/elements/boot-stack/bin/boot-stack-logs
@@ -2,8 +2,8 @@
 set -eu
 
 if [[ $EUID -ne 0 ]]; then
-   echo "ERROR: you must be root to run this" 1>&2
-   exit 1
+    echo "ERROR: you must be root to run this" 1>&2
+    exit 1
 fi
 
 scr_name=os-logs
@@ -17,11 +17,11 @@ caption always "%{-b ..}%-w%{+b ..}[[%n%f*%t]]%{-}%+w"
 eof
 
 for f in \
-  /var/log/upstart/nova-compute.log \
-  /var/log/upstart/nova-scheduler.log; do
-  if [ -e $f ]; then
-    echo "screen -t $(basename $f) sh -c \"tail -f $f | ccze\"" >> $scr_file
-  fi
+    /var/log/upstart/nova-compute.log \
+    /var/log/upstart/nova-scheduler.log; do
+    if [ -e $f ]; then
+        echo "screen -t $(basename $f) sh -c \"tail -f $f | ccze\"" >> $scr_file
+    fi
 done
 
 # XXX: Note that this is obsolete if the Neutron DHCP agent is in use.
