Fix libssl/crypto symlinks on Fedora
Fedora does not have the 1.0.0 versions of the .so files, so the
existing symlink step isn't working correctly.  This change looks
for any 1.0.* versions of libssl and libcrypto, so we shouldn't have
to update it for every minor version bump but it also won't
unintentionally pull in an incompatible version.

Change-Id: I8402d05be684337df70d8f48e6d2ac1ecc69eaf7
Related-Bug: #1304629

diff --git a/elements/mysql/install.d/20-galera-libssl-symlink b/elements/mysql/install.d/20-galera-libssl-symlink
--- a/elements/mysql/install.d/20-galera-libssl-symlink
+++ b/elements/mysql/install.d/20-galera-libssl-symlink
@@ -22,10 +22,22 @@ else
     fi
 fi
 
+LIBSSL_FILE=$(find $LIB_PREFIX -maxdepth 1 -type f -name "libssl.so.1.0.*" | head -n 1 || echo "")
+LIBCRYPTO_FILE=$(find $LIB_PREFIX -maxdepth 1 -type f -name "libcrypto.so.1.0.*" | head -n 1 || echo "")
+
+if [ -z LIBSSL_FILE ]; then
+    echo "Unable to find compatible libssl"
+    exit 1
+fi
+if [ -z LIBCRYPTO_FILE ]; then
+    echo "Unable to find compatible libcrypto"
+    exit 1
+fi
+
 if [ ! -L $LIB_PREFIX/libssl.so.6 ]; then
-    ln -s $LIB_PREFIX/libssl.so.1.0.0 $LIB_PREFIX/libssl.so.6
+    ln -s $LIBSSL_FILE $LIB_PREFIX/libssl.so.6
 fi
 
 if [ ! -L $LIB_PREFIX/libcrypto.so.6 ]; then
-    ln -s $LIB_PREFIX/libcrypto.so.1.0.0 $LIB_PREFIX/libcrypto.so.6
+    ln -s $LIBCRYPTO_FILE $LIB_PREFIX/libcrypto.so.6
 fi
