Automate network router setup.
If quantum.ovs.fixed_range is defined, that network will need to have a
router attached in order to reach the ec2 metadata service, or to reach
any floating ip ranges.

If quantum.floatingip_range is defined, that subnet will be created and
assigned to the default router. This is independent of openvswitch,
which is why it is not in the quantum.ovs namespace.

Change-Id: I7831be7435505885c77c9eeef33306eee546ac98

diff --git a/elements/quantum-network-node/os-refresh-config/post-configure.d/80-quantum-networking b/elements/quantum-network-node/os-refresh-config/post-configure.d/80-quantum-networking
--- a/elements/quantum-network-node/os-refresh-config/post-configure.d/80-quantum-networking
+++ b/elements/quantum-network-node/os-refresh-config/post-configure.d/80-quantum-networking
@@ -1,5 +1,8 @@
 #!/bin/bash
 set -eux
+set -o pipefail
+
+. /root/stackrc
 
 PUBLIC_INTERFACE=$(os-config-applier --key quantum.ovs.public_interface --key-default '')
 
@@ -9,6 +12,68 @@ ovs-vsctl --no-wait br-set-external-id br-ex bridge-id br-ex
 if [ -n "$PUBLIC_INTERFACE" ] ; then
     ovs-vsctl --no-wait -- --may-exist add-port br-ex $PUBLIC_INTERFACE
 fi
+
+find_cidr() {
+    local cidr=$1
+    # Determine subnet ID
+    local id=""
+    local subnets=$(quantum subnet-list --quote none -f csv -F id -F cidr)
+    for subnet in $subnets; do
+        id=${subnet%%,*}
+        this_cidr=${subnet##*,}
+        # Remove trailing \r from csv format
+        this_cidr=${this_cidr%?}
+        if [ "$this_cidr" = "$cidr" ] ; then
+            break
+        else
+            id=""
+        fi
+    done
+    echo $id
+}
+
+FIXED_RANGE=$(os-config-applier --key quantum.ovs.fixed_range --key-default '' --type netaddress)
+
+# Determine subnet ID
+id=$(find_cidr $FIXED_RANGE)
+if [ -z "$id" ] ; then
+    echo "Could not find $FIXED_RANGE in existing subnets. Aborting..."
+    exit 1
+fi
+
+echo $FIXED_RANGE has id $id
+
+# Ensure tenant network has route to metadata
+if ! quantum router-show default-router >/dev/null 2>&1 ; then
+    quantum router-create default-router
+fi
+
+if ! quantum router-port-list default-router -f csv -F fixed_ips | grep -q "$id" ; then
+    quantum router-interface-add default-router $id
+fi
+
+# Ensure defined floating ip range exists
+FLOATING_RANGE=$(os-config-applier --key quantum.floatingip_range --type netaddress --key-default '')
+if [ -n "$FLOATING_RANGE" ] ; then
+    # External net?
+    if ! quantum net-show ext-net >/dev/null 2>&1 ; then
+        quantum net-create ext-net --router:external=True
+    fi
+    id=$(find_cidr $FLOATING_RANGE)
+    if [ -z "$id" ] ; then
+        # id is set by command below
+	POOL_START=$(os-config-applier --key quantum.floatingip_start --type netaddress)
+	POOL_END=$(os-config-applier --key quantum.floatingip_end --type netaddress)
+        eval $(quantum subnet-create ext-net $FLOATING_RANGE --disable-dhcp \
+	    --allocation-pool start=$POOL_START,end=$POOL_END -f shell -c id|grep '^id=')
+    fi
+    # Attach it to default-router
+    if ! quantum router-port-list default-router -f csv -F fixed_ips | grep -q "$id" ; then
+        # Make ext-net the gateway
+        quantum router-gateway-set default-router ext-net
+    fi
+fi
+
 
 service quantum-metadata-agent restart
 service quantum-l3-agent restart
